name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Environment
        uses: guidepup/setup-action@0.1.3
      - name: npm ci and npm run ci
        run: |
          npm ci
          npm run ci